### ISSUE TITLE
[Feature Request] More conditions

### ISSUE THREAD

**Issue by supersaiyansubtlety** [NotSoEpic/fluid-interactions#1]
Would you consider allowing specification of more conditions?

For example y-level (min/max), biome (allow/deny list), biome temperature (allow/deny list), light level (min/max), dimension type (allow/deny list).

**Comment by BeeIsYou** [comment]
Added in version 1.1.0 👍

**Comment by supersaiyansubtlety** [comment]
Awesome, thanks!
