### ISSUE TITLE
How to make an Andesite generator?

### ISSUE THREAD

**Issue by Auxioni** [NotSoEpic/fluid-interactions#2]
### Issue ###
So I tried to make an Andesite generator, using the default json as an example, and it just doesn't work. Did I do something wrong?

### Attempt ###
```
{
  "interactions": [
    {
      "flowing": "minecraft:lava",
      "adjacent_fluid": "minecraft:water",
      "catalyst": "minecraft:andesite",
      "results": [
        {
          "block": "minecraft:andesite"
        }
      ]
    }
  ]
}
```

### Expected result ###
![Andesite generator](https://imagedelivery.net/aG82t-qDLn415HP9HHoOeg/242704eb-f727-48ac-3f98-5151d61d2400/original)

**Comment by BeeIsYou** [comment]
You need to define a weight for each entry, even if there is only 1
```
{
  "interactions": [
    {
      "flowing": "minecraft:lava",
      "adjacent_fluid": "minecraft:water",
      "catalyst": "minecraft:andesite",
      "results": [
        {
          "block": "minecraft:andesite",
          "weight": 1
        }
      ]
    }
  ]
}
```
I _have_ learnt how to do data-driven recipes since making this mod, and do plan on refactoring it eventually
